project:
  type: website

website:
  title: "Zhipei (Kim) Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



